//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuporteSolution.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuporteSolution.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap door_in {
            get {
                object obj = ResourceManager.GetObject("door_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///SET DIR=%~dp0%
        ///cd c:\temp
        ///%systemroot%\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -ExecutionPolicy Bypass -Command &quot;((new-object net.webclient).DownloadFile(&apos;https://chocolatey.org/install.ps1&apos;,&apos;install.ps1&apos;))&quot;
        ///%systemroot%\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -ExecutionPolicy Bypass -Command &quot;&amp; &apos;%DIR%install.ps1&apos; %*&quot;
        ///SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin.
        /// </summary>
        internal static string installChocolatey {
            get {
                return ResourceManager.GetString("installChocolatey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key {
            get {
                object obj = ResourceManager.GetObject("key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- saved from url=(0022)http://internet.e-mail --&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///&lt;!--
        ///.style1 {
        ///	font-size: small; 
        ///	color:#134E82;
        ///	font-weight: bold;
        ///}
        ///.style3 {
        ///	font-size: small;
        ///	font-weight: bold;
        ///	color: #134E82;
        ///}
        ///.style4 {font-size: x-small}
        ///.style5 {color: #000000}
        ///.style6 {
        ///	font-size: x-small;
        ///	color: #134E82;
        ///}
        ///.style7 {color: #000000; font-size: xx-small; }
        ///.style8 {font-size: xx-small}
        ///.style9 {
        ///	font-size: small;
        ///	font-weight: bold;
        ///	color: #114D81;
        ///}
        ///.style10 {color: #114D81}
        ///--&gt;
        ///&lt;/style&gt;
        ///&lt;tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModeloPadrao {
            get {
                return ResourceManager.GetString("ModeloPadrao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- saved from url=(0022)http://internet.e-mail --&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///&lt;!--
        ///.style1 {
        ///	font-size: small; 
        ///	color:#134E82;
        ///	font-weight: bold;
        ///}
        ///.style3 {
        ///	font-size: small;
        ///	font-weight: bold;
        ///	color: #134E82;
        ///}
        ///.style4 {font-size: x-small}
        ///.style5 {color: #000000}
        ///.style6 {
        ///	font-size: x-small;
        ///	color: #134E82;
        ///}
        ///.style7 {color: #000000; font-size: xx-small; }
        ///.style8 {font-size: xx-small}
        ///.style9 {
        ///	font-size: small;
        ///	font-weight: bold;
        ///	color: #114D81;
        ///}
        ///.style10 {color: #114D81}
        ///--&gt;
        ///&lt;/style&gt;
        ///&lt;tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModeloVendas2016 {
            get {
                return ResourceManager.GetString("ModeloVendas2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Trash {
            get {
                object obj = ResourceManager.GetObject("Trash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TrashMsf {
            get {
                object obj = ResourceManager.GetObject("TrashMsf", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
