//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuporteSolution.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"7zip.install --ignorechecksum;notepadplusplus --ignorechecksum;vlc --ignorechecksum;putty.install --ignorechecksum;thunderbird --ignorechecksum;libreoffice --ignorechecksum;hwinfo --ignorechecksum;googlechrome --version 49.0.2623.112 --ignorechecksum;firefox --version 52.0.2 --ignorechecksum;skype --version 7.36.0.101 --ignorechecksum;dotnet4.0 --ignorechecksum;tightvnc --version 2.7.1 --ignorechecksum")]
        public string ListaDePacotesParaInstalarNoWindowsXp {
            get {
                return ((string)(this["ListaDePacotesParaInstalarNoWindowsXp"]));
            }
            set {
                this["ListaDePacotesParaInstalarNoWindowsXp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("googlechrome;firefox;7zip.install;notepadplusplus;vlc;skype;dotnet4.5;putty.insta" +
            "ll;thunderbird;jre8;foxitreader;tightvnc;ie11;libreoffice;hwinfo")]
        public string ListaDePacotesParaInstalarNoWindows10 {
            get {
                return ((string)(this["ListaDePacotesParaInstalarNoWindows10"]));
            }
            set {
                this["ListaDePacotesParaInstalarNoWindows10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("googlechrome;firefox;7zip.install;notepadplusplus;vlc;skype;dotnet4.5;putty.insta" +
            "ll;thunderbird;jre8;foxitreader;tightvnc;ie11;libreoffice;hwinfo")]
        public string ListaDePacotesParaInstalarNoWindows7 {
            get {
                return ((string)(this["ListaDePacotesParaInstalarNoWindows7"]));
            }
            set {
                this["ListaDePacotesParaInstalarNoWindows7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("googlechrome;firefox;7zip.install;notepadplusplus;vlc;skype;dotnet4.5;putty.insta" +
            "ll;thunderbird;jre8;foxitreader;tightvnc;ie11;libreoffice;hwinfo")]
        public string ListaDePacotesParaInstalarNoWindows8 {
            get {
                return ((string)(this["ListaDePacotesParaInstalarNoWindows8"]));
            }
            set {
                this["ListaDePacotesParaInstalarNoWindows8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("googlechrome;firefox;7zip.install;notepadplusplus;vlc;skype;dotnet4.5;putty.insta" +
            "ll;thunderbird;jre8;foxitreader;tightvnc;ie11;libreoffice;hwinfo")]
        public string ListaDePacotesParaInstalarNoWindowsVista {
            get {
                return ((string)(this["ListaDePacotesParaInstalarNoWindowsVista"]));
            }
            set {
                this["ListaDePacotesParaInstalarNoWindowsVista"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\temp\\teste.txt")]
        public string ArquivoDeContinuidade {
            get {
                return ((string)(this["ArquivoDeContinuidade"]));
            }
            set {
                this["ArquivoDeContinuidade"] = value;
            }
        }
    }
}
